### ISSUE TITLE
Streamer Mode

### ISSUE THREAD

**Issue by pythonology** [BeatTogether/BeatTogether#7]
Add a streamer mode option which forces all connections onto relay servers.
This will need some implementation on the master server to allow the host to enable this.

**Comment by spjoes** [comment]
Maybe something like if you are about to click "show code" a popup will show up saying something like, "It seems your are streaming! Are you sure you want to show the code?". This I believe can all be done client side. Because, other than that idrk what else a streamer mode would be needed for than just not showing the code.

EDIT: Maybe it could also have the PC screen blank out or show a, "Streamer is entering code. Brb" when entering a code aswell so people dont snipe codes

**Comment by Kevman95** [comment]
This is also moot, so i am closing this.

With dedicated servers fully being in use for both official and BeatTogether, your IP address is always masked and shows the dedicated servers IP you got assigned to (we have multiple instances of this, so its never the same one each time). You can always deliberately hide the code within the lobby (you need to click it before it even shows up)
